### Spring properties
# Service registers under this name
spring:
  application:
    name: accounts-service
    
    
 # Discovery Server Access
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8888/eureka/
        
  # HTTP Server (Tomcat) Port
server: 
  port: 2222
  

       
  
  
     